export const certificateTypes = [
    "Participation",
    "Completion",
    "Achievement",
    "Excellence",
    "Recognition",
    "Appreciation",
    "Merit",
    "Honor",
    "Professional",
    "Academic",
    "Training",
    "Sports Achievement",
    "Language Proficiency",
    "First Aid",
    "Project Completion",
    "Leadership",
    "Volunteer",
    "Safety",
  ];